repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run --extra dev ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: ruff-format
        entry: uv run --extra dev ruff format
        language: system
        types: [python]
      - id: ty
        name: ty
        entry: uv run --extra dev ty check
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: uv run --extra dev pytest .
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
