services:
  web:
    build: .
    container_name: daily-learner
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/data
    command: uv run uvicorn endpoint:app --host 0.0.0.0 --port 8000
