import os

HEADING_MARKDOWN_REGEX = r"^#{1,6}\s*(.+)$"
BOLD_MARKDOWN_REGEX = r"\*\*(.+?)\*\*"
BOLD_SLACK_REGEX = r"*\1*"

MARKDOWN_RULES = [
    (HEADING_MARKDOWN_REGEX, BOLD_SLACK_REGEX),
    (BOLD_MARKDOWN_REGEX, BOLD_SLACK_REGEX),
]

DEFAULT_SCHEDULE_TIME = "09:30"
SCHEDULER_CHECK_INTERVAL_SECONDS = 60

SLACK_TIMESTAMP_MAX_AGE_SECONDS = 300

DB_NAME = os.getenv("DB_NAME", "books.db")
JOBS_DB_NAME = os.getenv("JOBS_DB_NAME", "jobs.db")
DEFAULT_PAGES_SPLIT = 15
GOOGLE_API_URL = "https://www.googleapis.com/books/v1/volumes?q="
