HEADING_MARKDOWN_REGEX = r"^#{1,6}\s*(.+)$"
BOLD_MARKDOWN_REGEX = r"\*\*(.+?)\*\*"

BOLD_SLACK_REGEX = r"*\1*"


MARKDOWN_RULES = [
    (HEADING_MARKDOWN_REGEX, BOLD_SLACK_REGEX),
    (BOLD_MARKDOWN_REGEX, BOLD_SLACK_REGEX),
]

DEFAULT_SCHEDULE_TIME = "09:30"
