name: CI

on:
  push:
    branches: [main]

jobs:
  common-jobs:
    uses: ./.github/workflows/common.yml
  deploy:
    runs-on: ubuntu-latest
    needs: common-jobs
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to prod
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/slack-bot-daily-summary
            git pull origin main
            docker compose build
            docker compose up -d
