name: Common Jobs

on:
  workflow_call:

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets && sudo make install

      - name: Run git-secrets scan
        run: |
          git secrets --scan
  code-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install uv
        run: pip install uv
      - name: Setup env file
        run: cp .env.example .env
      - name: Run tests
        run: uv run --extra dev pytest --cov-fail-under=100 --cov-report=xml
      - name: Run ruff
        run: uv run --extra dev ruff check
      - name: Run ty
        run: uv run --extra dev ty check
